nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/Cargo.toml
nucypher-core/src/address.rs
nucypher-core/src/arrays_as_bytes.rs
nucypher-core/src/fleet_state.rs
nucypher-core/src/lib.rs
nucypher-core/src/node_metadata.rs
nucypher-core/src/revocation_order.rs

- Makes `NodeMetadatPayload.decentralized_identity_evidence` a fixed size array (instead of a boxed slice)
- Adds a `NodeMetadataPayload::derive_worker_address()` method to derive the worker address from the evidence
- Makes all addresses passed as bytes in Python bindings fixed size arrays (so now their length will be checked by `pyo3`-generated wrapper code)
- Remove the unnecessary `PyResult` being returned from `to_bytes()` (it is infallible)
- `NodeMetadataPayload.canonical_address` and `RevocationOrder.ursula_address` were renamed to `staker_address`.
For reviewers:
- I mimicked the signed message format used in NuCypher code (`eth_account.messages.encode_defunct()`), which is marked as deprecated. Here's our chance to possibly change it to something more recent? (pinging @cygnusv) …

Add `NodeMetadataPayload::derive_worker_address()`

---

CHANGELOG.md
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/fleet_state.rs
nucypher-core/src/node_metadata.rs
nucypher-core/src/revocation_order.rs

Fixes #6
- Renamed `staker_address` to `staking_provider_address`
- Renamed `decentralized_identity_evidence` to `operator_signature`

Renames to match the new terminology

---

CHANGELOG.md
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/node_metadata.rs

This is a relaxed version of #12 (which will be archived). Here we only changed `NodeMetadataPayload.certificate_bytes` to `certificate_der` to provide a hint on what certificate format is expected. Since certificates are not currently used on Rust side, we can live without deserialization for a while.
See comments in #12 about the compatibility problems between Python- and Rust-created certificates. Perhaps it will be somehow fixed in the future, or we will actually need certificate objects on Rust side and will have to deal with the differences.
A compromise would be to just deserialize the certificate on the Rust side, but not expose it - it can be added later, since it won't break backward compatibility. It just feels silly to do all the deserialization work and then not use the …

Be more specific about what certificate format is expected in NodeMetadataPayload

---

CHANGELOG.md
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/address.rs
nucypher-core/src/hrac.rs
nucypher-core/src/key_frag.rs
nucypher-core/src/lib.rs
nucypher-core/src/node_metadata.rs
nucypher-core/src/reencryption.rs
nucypher-core/src/revocation_order.rs

- added a `HRAC::SIZE` constant and moved `ADDRESS_SIZE` to `Address::SIZE`
- added `HRAC.from_bytes()` in Python bindings to match WASM bindings
- renamed `RevocationOrder::verify_signature()` into `verify()` and made it return a Result<(Address, EncryptedKeyFrag)>. Correspondingly, made `RevocationOrder.staking_provider_address` private.
- made `MetadataResponse::verify()` and `ReencryptionResponse::verify()` return a `Result` instead of `Option`
- added `VerificationError` for the use of verification methods above

Api cleanup

---

.github/workflows/wheels.yml

- bump `cibuildwheel` version
- disable builds for Py3.6 (`PyO3` does not support it anymore)
- use the release branch for `pypa/gh-action-pypi-publish`
- add `long_description` to the Python package metadata

Update Python wheel building scripts.

---

CHANGELOG.md
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core/Cargo.toml
nucypher-core/src/fleet_state.rs
nucypher-core/src/hrac.rs

- Add `Display` impl for `HRAC` and `FleetStateChecksum`
- Expose it in the bindings as `__str__()` for Python, and `toString()` for WASM

Add `Display` impl for `HRAC` and `FleetStateChecksum`

---

CHANGELOG.md
nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs

- use `box_ref()` throughout
- add missing `conditions` getters in WASM bindings
- add missing attribute declarations in Python typing stubs

Small fixes after the introduction of conditions

---

.github/workflows/nucypher-core.yml
CHANGELOG.md
nucypher-core-python/Cargo.toml
nucypher-core-python/nucypher_core/__init__.py
nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/examples/node/src/main.test.ts
nucypher-core-wasm/examples/node/src/main.ts
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/Cargo.toml
nucypher-core/src/node_metadata.rs

- Use a workaround with `wasm-bindgen-derive` to support `Option<&T>` and `Vec<&T>` arguments, and `Vec<T>` and tuple return values, with correct TypeScript annotations
- Remove the instances of Builder pattern and the use of `serde` for argument passing.
- Use `Address` instead of plain bytes in arguments and return values (both in WASM and Python bindgins). Export the `Address` type.
- Use `js_sys::Error` instead of just `JsValue` in results.
- Rust-side and JS-side WASM tests updated
- Added JS-side tests to CI
- Exported `Address` in `__init__.py`

Bindings simplification

---

CHANGELOG.md
nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/src/lib.rs
nucypher-core-wasm/examples/node/src/main.test.ts
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/key_frag.rs
nucypher-core/src/reencryption.rs
nucypher-core/src/treasure_map.rs

- Take an iterable of `(Capsule, VerifiedCapsuleFrag)` tuples `ReencryptionResponse::new()` (and change bindings correspondingly)
- Replace `Iterable` with `Sequence` in Python bindgins: PyO3 cannot take generators as parameters.
- `AuthorizedKeyFrag.verify()`, `ReencryptionResponse.verify()`, and `AuthorizedTreasureMap.verify()` now consume `self`, to match Umbral and the other `nucypher-core`'s `verify()` methods.

Take an iterable of capsule and vcfrag in `ReencryptionResponse` constructor

---

CHANGELOG.md
nucypher-core-python/src/lib.rs

Finish up introducing `Address` type in the spots forgotten in #34. Namely, in Python bindings:
- in `TreasureMap.destinations()`
- in `RetrievalKit.queried_addresses()`
- in `NodeMetadata.staking_provider_address()`

Make the remaining methods returning Addresses strictly typed

---

.github/workflows/nucypher-core.yml
CHANGELOG.md
nucypher-core-python/Cargo.toml
nucypher-core-python/nucypher_core/umbral.pyi
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/examples/node/src/main.test.ts
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/Cargo.toml
nucypher-core/src/address.rs
nucypher-core/src/hrac.rs
nucypher-core/src/key_frag.rs
nucypher-core/src/message_kit.rs
nucypher-core/src/node_metadata.rs
nucypher-core/src/reencryption.rs
nucypher-core/src/retrieval_kit.rs
nucypher-core/src/revocation_order.rs
nucypher-core/src/treasure_map.rs
nucypher-core/src/versioning.rs

`umbral-pre` switched to using `serde` throughout (https://github.com/nucypher/rust-umbral/pull/110), which changes the ABI of protocol objects here.
- Bumped `umbral-pre` to 0.8, `rmp-serde` to 1.x, `pyo3` to 0.17
- Bumped MSRV to 1.63 because the compilers before can't derive some types in some generic constructions in `nucypher-core-wasm/src/lib.rs`.
- Major protocol versions bumped
- Updated `umbral.pyi`
- Updates for the changes in `umbral-pre` API
- Using `messagepack_serialize()` as the standard serialization for signing purposes

Update for the changed umbral-pre API

---

.github/workflows/nucypher-core.yml
.github/workflows/workspace.yml
PUBLISHING.md
README.md
nucypher-core-python/README.md
nucypher-core-python/setup.py
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/package.template.json
nucypher-core/Cargo.toml
nucypher-core/README.md

Fixes some leftover references to `master` in the GitHub actions configuration and documentation.

Renames branch master -> main

---

.github/workflows/nucypher-core.yml
Cargo.lock
Cargo.toml
nucypher-core-python/Cargo.toml
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/examples/node/package.json
nucypher-core-wasm/examples/node/src/main.test.ts
nucypher-core-wasm/examples/node/yarn.lock
nucypher-core-wasm/node_modules/.yarn-integrity
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/Cargo.toml
nucypher-core/src/dkg.rs
nucypher-core/src/lib.rs
nucypher-core/src/node_metadata.rs

- Closes #49 
- Changes in `ferveo` are tracked here: https://github.com/nucypher/ferveo/pull/119
- Re-applies the WASM build fix from: https://github.com/nucypher/nucypher-core/pull/52#discussion_r1193016251
- Questions
- Should we rename `PublicKey` to `UmbralPublicKey` and `FerveoPublicKey` respectively? Technically, it's sufficient to rename one of them, `FerveoPublicKey`.
- For now, renaming to `FerveoPublicKey`

Integrate with `ferveo` crate

---

nucypher-core/src/dkg.rs

- Tests failing for the same reason #52 used to fail. Let's merge #52 in, and rebase this PR over it.
- Alternatively we can just merge it since it's a docstring change

Clarify Ferveo variant usage in docs

---

Cargo.lock
nucypher-core-python/Cargo.toml
nucypher-core-wasm/Cargo.toml
nucypher-core/Cargo.toml

- Feature
-  1
- Bumps `rust-umbral` version
- `0.10.0` contains a [fix for compatibility issue](https://github.com/nucypher/rust-umbral/pull/122) with `ferveo`
- We need it to release a new `nucypher-core` version with `ferveo` support

Bump `umbral-pre` to `0.10.0`

---

CHANGELOG.md
Cargo.lock
nucypher-core-python/Cargo.toml
nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/nucypher_core/ferveo.py
nucypher-core-python/nucypher_core/ferveo.pyi
nucypher-core-python/nucypher_core/umbral.py
nucypher-core-python/setup.py
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core/Cargo.toml

**To Do:**
- Feature
- 2
- Implements issues caught during integration with `nucypher`
> - Fixes #...
- Discovering and addressing changes before signing off on the new `nucypher-core` version
- Finalizing `nucypher` integration
- Please consider reviewing https://github.com/nucypher/nucypher/pull/3135 first

Implement feedback from `nucypher` integration

---

CHANGELOG.md
nucypher-core-python/nucypher_core/ferveo.pyi

- Bugfix
- 1
- Fixes a typo in the stub for `Keypair.secure_randomness_size()`

Fix a typo in Ferveo type stubs

---

CHANGELOG.md
Cargo.lock
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/src/lib.rs
nucypher-core/Cargo.toml
nucypher-core/src/conditions.rs

- Feature
- 2
- Adds `equals` method to WASM bindings
- Attempts to remove boilerplate code with macros
- #56 
- Enables comparison operations in JavaScript
- Uses changes from [an unreleased `ferveo` version](https://github.com/nucypher/ferveo/commit/c259bf774939340fca0c2b90d3ee2fb2aa4ad947)
- Are macros introduced in this PR a good idea? Should I continue working on them (in this PR?). They removed some lines of code but on the other hand, they are not compatible with all protocol objects. For example, `generate_to_bytes` may only replace some `to_bytes` methods and so will require more work / another macro to be introduced.
- No downstream effect on …

Add equals method to protocol objects in WASM bindings

---

CHANGELOG.md
nucypher-core/src/dkg.rs

`SessionStaticKey` protocol objects had varied lengths due to serialization to vector of integers instead of bytestrings. This fixes that.
> - Fixes #...
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?

Use custom (de)serialization for SessionStaticKey into bytes

---

CHANGELOG.md
Cargo.lock
nucypher-core-python/Cargo.toml
nucypher-core-python/nucypher_core/ferveo.py
nucypher-core-python/nucypher_core/ferveo.pyi
nucypher-core-wasm/Cargo.toml
nucypher-core/Cargo.toml
nucypher-core/src/conditions.rs

- Bugfix
- 1
- Replaces tuple usage with a concrete `ValidatorMessage` type in Python Bindings
- Refers to: https://github.com/nucypher/ferveo/issues/129
- Closes: https://github.com/nucypher/nucypher-core/issues/62
- To fix the corresponding issue. See: https://github.com/nucypher/ferveo/pull/131
- Uses changes from [an unreleased `ferveo` version](https://github.com/nucypher/ferveo/commit/4aeda15dd749694416f62fda0504f64bcbe2b444)
- This PR closes https://github.com/nucypher/nucypher-core/issues/62 since the `ferveo` version used is the child of the changes mentioned in the issue

Fix missing `ValidatorMessage` stub in Python bindings

---

Cargo.lock
nucypher-core-python/Cargo.toml
nucypher-core-wasm/Cargo.toml
nucypher-core/Cargo.toml

-  Other
- 1
- Replace GH dependency with a crate

Use `ferveo-pre-release@0.1.0-alpha.10`

---

Cargo.lock
nucypher-core-python/Cargo.toml
nucypher-core-python/src/lib.rs
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/src/lib.rs
nucypher-core/Cargo.toml
nucypher-core/src/dkg.rs
nucypher-core/src/lib.rs

- Feature
- 1
- Implement changes required for compatibility with an upcoming Ferveo release
- Refers to: https://github.com/nucypher/ferveo/pull/136
- Refers to: https://github.com/nucypher/ferveo/pull/134
- Refers to: https://github.com/nucypher/ferveo/pull/137
- Fixes: #68 
- Need to keep track of upcoming changes in Ferveo and test them before the release
- Requires MINOR version bump because of a breaking change in #136
- Downstream changes:
- https://github.com/nucypher/nucypher/pull/3171

Tracking changes for `ferveo-pre-release@0.3.0` update

---

.github/workflows/nucypher-core.yml
Cargo.lock
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/access_control.rs
nucypher-core/src/threshold_message_kit.rs

- Other
-  1
- Avoids `unwrap()`, and handles errors gracefully instead
- Replaces `PartialEq` impl. with a `derive` macro
- Also throwing in a commit to address changes in the new Rust `stable` (1.7.2)
> - Fixes #...
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
- Based on #74 - Please review & merge it first
- The CI failure is caused by MSRV incompatibility. To be fixed.

Address PR comments in #74

---

.github/workflows/nucypher-core.yml
Cargo.lock

- Other
- 1
- Installs `wasm-pack` from a precompiled binary
- Fixes a listing issue on Rust `stable`
- Copies changes from https://github.com/nucypher/ferveo/pull/159
- Some child dependencies in `wasm-pack` an `wasm-opt` get updated from time to time and that causes MSRV float
- With these changes, we should be able to avoid that in the future, and hence avoid CI breaking from time to time

chore(ci): use binary wasm-pack distribution

---

CHANGELOG.md
Cargo.lock
nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/src/lib.rs
nucypher-core-wasm/src/lib.rs
nucypher-core-wasm/tests/wasm.rs
nucypher-core/src/access_control.rs
nucypher-core/src/dkg.rs
nucypher-core/src/threshold_message_kit.rs

…ata and AccessControlPolicy.
> High-level idea of the changes introduced in this PR. 
> List relevant API changes (if any), as well as related PRs and issues.
Related to #76 .
Conditions should not be optional for CBD - it's kind of the whole point.
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?
Already ran parts of the test suite locally with `nucypher` to test python bindings. There are no downstream changes necessary for `nucypher` other than an updated `nucypher-core` dependency, because conditions were not optional for CBD functionality in `nucypher` anyway.

Conditions should not be optional for CBD types

---

nucypher-core-python/nucypher_core/__init__.pyi
nucypher-core-python/nucypher_core/ferveo.pyi

- Bugfix
- 1
Fixes some incorrect Python typing stubs:
- `ThresholdMessageKit.decrypt_with_shared_secret()` - added a missing `bytes` return type
- `combine_decryption_shares_simple()` - replaced the incorrect `bytes` return type with `SharedSecret`

Fix Python typing stubs

---

.bumpversion.cfg
CHANGELOG.md
Cargo.lock
PUBLISHING.md
nucypher-core-python/Cargo.toml
nucypher-core-python/setup.py
nucypher-core-wasm-bundler/package-lock.json
nucypher-core-wasm-bundler/package.json
nucypher-core-wasm/Cargo.toml
nucypher-core-wasm/package.template.json
nucypher-core/Cargo.toml

- Other
- 1
- Documents and releases prior changes
- Removing publishing docs for old WASM packaging
- Releasing a new npm package will help with some packaging issues in `taco-web`
- Release Python package after merging: https://github.com/nucypher/rust-umbral/actions/workflows/wheels.yml
- Also squeezing in a `@nucypher/nucypher-core:0.14.1`, because I accidentally released WASM bundled with the old method instead of the new inlined method

Release v0.14.0

---

.github/dependabot.yml
.github/workflows/nucypher-core.yml
.github/workflows/wheels.yml
nucypher-core-wasm-bundler/package-lock.json
nucypher-core-wasm-bundler/package.json
nucypher-core-wasm-bundler/src/index_node.ts
nucypher-core-wasm/src/lib.rs

-  Bugfix
-  1
- Diagnoses and fixes an issue where `@nucypher/nucypher-core` would not work for Node.js 18+ users
- [These lines](https://github.com/nucypher/nucypher-core/pull/94/files#diff-663b6ec842422fe7a0c6e87f80ffa6a3f29b0cdfc5a6683da7167b1b4b10b006R5-R8) contains the actual fix
- This PR contains `@nucypher/nucypher-core:0.14.5` release. The version bump from `0.14.1` to `0.14.5` is the aftermath of previous try-and-fail attempts at building a correct package. Functionally, these versions (`0.14.1-5`) are the same. A `0.14.5` tag has been created. 
- Fixes: #93

Fix NodeJS compatibilty across different versions
